module.exports = {
  acceptCharset: 'accept-charset',
  httpEquiv: 'http-equiv',
  htmlFor: 'for',

  // Lower case attributes
  crossOrigin: 'crossorigin',
  noModule: 'nomodule',
  'autoComplete': 'autocomplete',
  'autoPlay': 'autoplay',
  'cellPadding': 'cellpadding',
  'cellSpacing': 'cellspacing',
  'classID': 'classid',
  'codeBase': 'codebase',
  'colSpan': 'colspan',
  'contextMenu': 'contextmenu',
  'dateTime': 'datetime',
  'encType': 'enctype',
  'formAction': 'formaction',
  'formEncType': 'formenctype',
  'formMethod': 'formmethod',
  'formNoValidate': 'formnovalidate',
  'formTarget': 'formtarget',
  'frameBorder': 'frameborder',
  'hrefLang': 'hreflang',
  'imageSizes': 'imagesizes',
  'imageSrcSet': 'imagesrcset',
  'isMap': 'ismap',
  'keyParams': 'keyparams',
  'keyType': 'keytype',
  'marginHeight': 'marginheight',
  'marginWidth': 'marginwidth',
  'maxLength': 'maxlength',
  'mediaGroup': 'mediagroup',
  'minLength': 'minlength',
  'noValidate': 'novalidate',
  'radioGroup': 'radiogroup',
  'readOnly': 'readonly',
  'referrerPolicy': 'referrerpolicy',
  'rowSpan': 'rowspan',
  'srcDoc': 'srcdoc',
  'srcLang': 'srclang',
  'srcSet': 'srcset',
  'useMap': 'usemap',
  'fetchPriority': 'fetchPriority'
};